import { mysqlTable, mysqlSchema, AnyMySqlColumn, int, varchar, text, timestamp, index, foreignKey, mysqlEnum, date, tinyint, bigint } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const aboutPage = mysqlTable("aboutPage", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 255 }).default('Sobre Nós').notNull(),
	subtitle: text(),
	mainContent: text(),
	mission: text(),
	vision: text(),
	values: text(),
	teamDescription: text(),
	imageUrl: text(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const albumGuests = mysqlTable("albumGuests", {
	id: int().autoincrement().notNull(),
	collectionId: int().notNull(),
	email: varchar({ length: 320 }).notNull(),
	name: varchar({ length: 255 }),
	relationship: varchar({ length: 100 }),
	viewedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_collection").on(table.collectionId),
	index("idx_email").on(table.email),
]);

export const announcementViews = mysqlTable("announcement_views", {
	id: int().autoincrement().notNull(),
	announcementId: int().notNull().references(() => announcements.id, { onDelete: "cascade" } ),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	dismissed: tinyint().default(0).notNull(),
	viewedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const announcements = mysqlTable("announcements", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 255 }).notNull(),
	message: text().notNull(),
	type: mysqlEnum(['urgent','important','info']).default('info').notNull(),
	targetPlan: mysqlEnum(['all','starter','pro','enterprise']).default('all').notNull(),
	isActive: tinyint().default(1).notNull(),
	expiresAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdBy: int().notNull(),
	tenantId: int().default(0).notNull(),
});

export const appointmentExtras = mysqlTable("appointmentExtras", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull(),
	description: varchar({ length: 255 }).notNull(),
	price: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const appointmentPhotos = mysqlTable("appointmentPhotos", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull(),
	photoUrl: text().notNull(),
	thumbnailUrl: text(),
	fileName: varchar({ length: 255 }).notNull(),
	fileSize: int(),
	isSelectedByClient: tinyint().default(0).notNull(),
	uploadedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const appointments = mysqlTable("appointments", {
	id: int().autoincrement().notNull(),
	serviceId: int(),
	userId: int(),
	clientName: varchar({ length: 255 }).notNull(),
	clientEmail: varchar({ length: 320 }).notNull(),
	clientPhone: varchar({ length: 50 }),
	appointmentDate: timestamp({ mode: 'string' }).notNull(),
	status: mysqlEnum(['pending','awaiting_payment','confirmed','session_done','editing','awaiting_selection','final_editing','delivered','cancelled']).default('pending').notNull(),
	notes: text(),
	contractUrl: text(),
	contractSigned: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	appointmentTime: varchar({ length: 10 }),
	eventLocation: text(),
	numberOfPeople: int(),
	estimatedDuration: varchar({ length: 50 }),
	adminNotes: text(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	selectionApproved: tinyint().default(0).notNull(),
	selectionApprovedAt: timestamp({ mode: 'string' }),
	paymentStatus: mysqlEnum(['pending','awaiting_payment','partial','paid','failed','refunded']).default('pending'),
	finalPrice: int(),
	stripeSessionId: varchar({ length: 255 }),
	stripePaymentIntentId: varchar({ length: 255 }),
	paidAt: timestamp({ mode: 'string' }),
	paymentMethod: mysqlEnum(['cash','bank_transfer','stripe']),
	paidAmount: int().default(0),
	slug: varchar({ length: 255 }),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_appointments_tenantId").on(table.tenantId),
	index("idx_appointments_status").on(table.status),
	index("idx_appointments_serviceId").on(table.serviceId),
]);

export const bannerSlides = mysqlTable("bannerSlides", {
	id: int().autoincrement().notNull(),
	slideType: mysqlEnum(['image','video']).default('image').notNull(),
	imageUrl: text(),
	videoUrl: text(),
	title: varchar({ length: 255 }),
	description: text(),
	buttonText: varchar({ length: 100 }),
	buttonLink: varchar({ length: 500 }),
	isActive: tinyint().default(1).notNull(),
	sortOrder: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	displayOn: mysqlEnum(['photography','video','both']).default('both').notNull(),
	tenantId: int().default(1).notNull(),
});

export const blockedDates = mysqlTable("blockedDates", {
	id: int().autoincrement().notNull(),
	reason: varchar({ length: 255 }),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	startDate: timestamp({ mode: 'string' }).notNull(),
	endDate: timestamp({ mode: 'string' }).notNull(),
	tenantId: int().default(1).notNull(),
});

export const clientMessages = mysqlTable("clientMessages", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull(),
	senderId: int().notNull(),
	senderRole: mysqlEnum(['admin','client']).notNull(),
	message: text().notNull(),
	fileUrl: text(),
	fileName: varchar({ length: 255 }),
	isRead: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const collections = mysqlTable("collections", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	slug: varchar({ length: 255 }).notNull(),
	description: text(),
	coverImageUrl: text(),
	isFeatured: tinyint().default(0).notNull(),
	isPublic: tinyint().default(1).notNull(),
	sortOrder: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	appointmentId: int(),
	layoutType: mysqlEnum(['grid','masonry','fullscreen']).default('masonry').notNull(),
	// you can use { mode: 'date' }, if you want to have Date as type for this column
	eventDate: date({ mode: 'string' }),
	password: varchar({ length: 255 }),
	salesEnabled: tinyint().default(0).notNull(),
	publicSlug: varchar({ length: 255 }),
	pricePerPhoto: int().default(2500).notNull(),
	tenantId: int().default(1).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("collections_slug_unique").on(table.slug),
	index("collections_publicSlug_unique").on(table.publicSlug),
	index("idx_collections_tenantId").on(table.tenantId),
	index("idx_collections_appointmentId").on(table.appointmentId),
	index("idx_collections_slug").on(table.slug),
]);

export const contactInfo = mysqlTable("contactInfo", {
	id: int().autoincrement().notNull(),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	whatsapp: varchar({ length: 50 }),
	address: text(),
	city: varchar({ length: 100 }),
	state: varchar({ length: 100 }),
	zipCode: varchar({ length: 20 }),
	country: varchar({ length: 100 }).default('Brasil'),
	mapLatitude: varchar({ length: 50 }),
	mapLongitude: varchar({ length: 50 }),
	instagramUrl: text(),
	facebookUrl: text(),
	linkedinUrl: text(),
	twitterUrl: text(),
	youtubeUrl: text(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const contractTemplates = mysqlTable("contractTemplates", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	content: text().notNull(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	tenantId: int().default(1).notNull(),
});

export const coupons = mysqlTable("coupons", {
	id: int().autoincrement().notNull(),
	code: varchar({ length: 50 }).notNull(),
	discountType: mysqlEnum(['percentage','fixed']).notNull(),
	discountValue: int().notNull(),
	minPurchase: int().default(0),
	maxUses: int(),
	usedCount: int().default(0).notNull(),
	expiresAt: timestamp({ mode: 'string' }),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("coupons_code_unique").on(table.code),
]);

export const downloadLogs = mysqlTable("downloadLogs", {
	id: int().autoincrement().notNull(),
	collectionId: int().notNull(),
	userId: int().notNull(),
	downloadType: mysqlEnum(['single_photo','all_photos_zip']).notNull(),
	photoId: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const downloadPermissions = mysqlTable("downloadPermissions", {
	id: int().autoincrement().notNull(),
	collectionId: int().notNull(),
	allowDownload: tinyint().default(0).notNull(),
	downloadExpiresAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("downloadPermissions_collectionId_unique").on(table.collectionId),
]);

export const finalAlbums = mysqlTable("finalAlbums", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull(),
	photoUrl: text().notNull(),
	thumbnailUrl: text(),
	fileName: varchar({ length: 255 }).notNull(),
	fileSize: int(),
	order: int().default(0).notNull(),
	uploadedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_finalAlbums_appointmentId").on(table.appointmentId),
	index("idx_finalAlbums_tenantId").on(table.tenantId),
]);

export const framePricing = mysqlTable("framePricing", {
	id: int().autoincrement().notNull(),
	size: varchar({ length: 50 }).notNull(),
	sizeLabel: varchar({ length: 100 }).notNull(),
	basePrice: int().notNull(),
	isActive: tinyint().default(1).notNull(),
	sortOrder: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("framePricing_size_unique").on(table.size),
]);

export const frameTypes = mysqlTable("frameTypes", {
	id: int().autoincrement().notNull(),
	type: varchar({ length: 50 }).notNull(),
	typeLabel: varchar({ length: 100 }).notNull(),
	additionalPrice: int().notNull(),
	isActive: tinyint().default(1).notNull(),
	sortOrder: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("frameTypes_type_unique").on(table.type),
]);

export const mediaItems = mysqlTable("mediaItems", {
	id: int().autoincrement().notNull(),
	collectionId: int(),
	mediaType: mysqlEnum(['photo','video']).notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	originalUrl: text().notNull(),
	previewUrl: text(),
	thumbnailUrl: text(),
	priceDigital: int().default(0),
	width: int(),
	height: int(),
	isPublic: tinyint().default(1).notNull(),
	isFeatured: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	price: int().default(0).notNull(),
	isStock: tinyint().default(0).notNull(),
	category: mysqlEnum(['paisagem','carros','pessoas','eventos','produtos','outros']),
	stockDescription: text(),
	isFavorite: tinyint().default(0).notNull(),
	availableForSale: tinyint().default(0).notNull(),
	watermarkedUrl: text(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_mediaItems_collectionId").on(table.collectionId),
	index("idx_mediaItems_tenantId").on(table.tenantId),
]);

export const orderItems = mysqlTable("orderItems", {
	id: int().autoincrement().notNull(),
	orderId: int().notNull(),
	mediaId: int(),
	itemType: mysqlEnum(['digital','print']).notNull(),
	itemName: varchar({ length: 255 }).notNull(),
	price: int().notNull(),
	quantity: int().default(1).notNull(),
	printSize: varchar({ length: 50 }),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const orders = mysqlTable("orders", {
	id: int().autoincrement().notNull(),
	userId: int(),
	customerName: varchar({ length: 255 }).notNull(),
	customerEmail: varchar({ length: 320 }).notNull(),
	totalAmount: int().notNull(),
	discountAmount: int().default(0).notNull(),
	finalAmount: int().notNull(),
	status: mysqlEnum(['pending','paid','processing','completed','cancelled']).default('pending').notNull(),
	stripePaymentId: varchar({ length: 255 }),
	couponCode: varchar({ length: 50 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const paymentTransactions = mysqlTable("paymentTransactions", {
	id: int().autoincrement().notNull(),
	appointmentId: int().notNull(),
	amount: int().notNull(),
	paymentMethod: mysqlEnum(['cash','bank_transfer','stripe']).notNull(),
	status: mysqlEnum(['pending','completed','failed','refunded']).default('pending').notNull(),
	stripePaymentIntentId: varchar({ length: 255 }),
	notes: text(),
	paidAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const photoComments = mysqlTable("photoComments", {
	id: int().autoincrement().notNull(),
	photoId: int().notNull(),
	appointmentId: int().notNull(),
	clientEmail: varchar({ length: 255 }).notNull(),
	comment: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
});

export const photoSales = mysqlTable("photoSales", {
	id: int().autoincrement().notNull(),
	photoId: int().notNull(),
	buyerEmail: varchar({ length: 320 }).notNull(),
	buyerName: varchar({ length: 255 }).notNull(),
	amount: int().notNull(),
	stripeSessionId: varchar({ length: 255 }).notNull(),
	stripePaymentIntentId: varchar({ length: 255 }),
	status: mysqlEnum(['pending','paid','failed','refunded']).default('pending').notNull(),
	downloadToken: varchar({ length: 64 }),
	downloadExpiresAt: timestamp({ mode: 'string' }),
	downloadCount: int().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	paidAt: timestamp({ mode: 'string' }),
	productType: mysqlEnum(['digital','framed']).default('digital').notNull(),
	frameSize: varchar({ length: 50 }),
	frameType: varchar({ length: 50 }),
	collectionId: int(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("photoSales_downloadToken_unique").on(table.downloadToken),
]);

export const photoSelections = mysqlTable("photoSelections", {
	id: int().autoincrement().notNull(),
	mediaItemId: int().notNull(),
	collectionId: int().notNull(),
	isSelected: tinyint().default(0).notNull(),
	clientFeedback: text(),
	editedPhotoUrl: text(),
	status: mysqlEnum(['pending','editing','completed']).default('pending').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_photoSelections_collectionId").on(table.collectionId),
	index("idx_photoSelections_isSelected").on(table.isSelected),
	index("idx_photoSelections_tenantId").on(table.tenantId),
]);

export const portfolioItems = mysqlTable("portfolioItems", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	location: varchar({ length: 255 }),
	story: text(),
	imageUrl: text(),
	thumbnailUrl: text(),
	sortOrder: int().default(0).notNull(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	showOnHome: tinyint().default(0).notNull(),
	type: mysqlEnum(['photo','video']).default('photo').notNull(),
	videoUrl: text(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_portfolioItems_tenantId").on(table.tenantId),
	index("idx_portfolioItems_isActive").on(table.isActive),
	index("idx_portfolioItems_showOnHome").on(table.showOnHome),
]);

export const products = mysqlTable("products", {
	id: int().autoincrement().notNull(),
	collectionId: int(),
	type: mysqlEnum(['digital','print','service']).notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	originalUrl: text(),
	originalKey: text(),
	previewUrl: text(),
	previewKey: text(),
	thumbnailUrl: text(),
	thumbnailKey: text(),
	videoUrl: text(),
	videoKey: text(),
	priceDigital: int().default(0),
	pricePrint: int().default(0),
	priceService: int().default(0),
	width: int(),
	height: int(),
	fileSize: int(),
	mimeType: varchar({ length: 100 }),
	printOptions: text(),
	isPublic: tinyint().default(1).notNull(),
	isFeatured: tinyint().default(0).notNull(),
	ftpPath: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const services = mysqlTable("services", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	slug: varchar({ length: 255 }).notNull(),
	description: text(),
	price: int().notNull(),
	duration: int(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	serviceType: mysqlEnum(['photography','video','both']).default('photography').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("services_slug_unique").on(table.slug),
	index("idx_services_tenantId").on(table.tenantId),
	index("idx_services_isActive").on(table.isActive),
]);

export const siteConfig = mysqlTable("siteConfig", {
	id: int().autoincrement().notNull(),
	activeTemplate: varchar({ length: 50 }).default('centro-classico').notNull(),
	siteName: varchar({ length: 255 }).default('Lirolla').notNull(),
	siteTagline: text(),
	logoUrl: text(),
	primaryColor: varchar({ length: 50 }).default('#000000'),
	accentColor: varchar({ length: 50 }).default('#C9A961'),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	businessMode: mysqlEnum(['photography_only','video_only','both']).default('photography_only').notNull(),
	aboutTitle: varchar({ length: 255 }),
	aboutContent: text(),
	aboutImage: text(),
	aboutMission: text(),
	aboutVision: text(),
	aboutValues: text(),
	servicesIntro: text(),
	contactPhone: varchar({ length: 50 }),
	contactEmail: varchar({ length: 255 }),
	contactWhatsApp: varchar({ length: 50 }),
	contactAddress: text(),
	socialInstagram: varchar({ length: 255 }),
	socialFacebook: varchar({ length: 255 }),
	socialYouTube: varchar({ length: 255 }),
	stockPhotosEnabled: tinyint().default(0).notNull(),
	templateName: varchar({ length: 100 }),
	templateDescription: text(),
	parallaxEnabled: tinyint().default(0).notNull(),
	parallaxImageUrl: text(),
	parallaxTitle: varchar({ length: 255 }),
	parallaxSubtitle: text(),
	paymentStripeEnabled: tinyint().default(1).notNull(),
	paymentBankTransferEnabled: tinyint().default(0).notNull(),
	paymentBankDetails: text(),
	paymentCashEnabled: tinyint().default(0).notNull(),
	paymentCashInstructions: text(),
	baseCountry: varchar({ length: 100 }).default('Brasil'),
	baseCurrency: varchar({ length: 10 }).default('BRL'),
	currencySymbol: varchar({ length: 10 }).default('R$'),
	timezone: varchar({ length: 100 }).default('America/Sao_Paulo'),
	phoneCountryCode: varchar({ length: 10 }).default('+55'),
	tenantId: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	siteThemeLayout: mysqlEnum(['classic','sidebar','wedding','wedding-videos']).default('classic').notNull(),
	siteThemeMode: mysqlEnum(['light','dark']).default('dark').notNull(),
	siteThemeAccentColor: mysqlEnum(['red','black','blue']).default('red').notNull(),
});

export const stockPhotos = mysqlTable("stockPhotos", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	category: mysqlEnum(['paisagem','carros','pessoas','eventos','produtos','outros']).notNull(),
	originalUrl: text().notNull(),
	thumbnailUrl: text(),
	previewUrl: text(),
	price: int().default(0).notNull(),
	width: int(),
	height: int(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	frameEnabled: tinyint().default(0).notNull(),
	tenantId: int().default(1).notNull(),
});

export const subscriptions = mysqlTable("subscriptions", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull().references(() => tenants.id, { onDelete: "cascade" } ),
	plan: mysqlEnum(['starter','pro','enterprise','full']).default('starter').notNull(),
	status: mysqlEnum(['trialing','active','past_due','cancelled','paused']).default('trialing').notNull(),
	storageLimit: bigint({ mode: "number" }).default(10737418240).notNull(),
	galleryLimit: int().default(10).notNull(),
	extraStorage: bigint({ mode: "number" }).default(0).notNull(),
	extraGalleries: int().default(0).notNull(),
	currentPeriodStart: timestamp({ mode: 'string' }),
	currentPeriodEnd: timestamp({ mode: 'string' }),
	cancelAtPeriodEnd: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	canceledAt: timestamp("canceled_at", { mode: 'string' }),
},
(table) => [
	index("idx_subscriptions_status").on(table.status),
	index("idx_subscriptions_tenantId").on(table.tenantId),
]);

export const supportTicketReplies = mysqlTable("support_ticket_replies", {
	id: int().autoincrement().notNull(),
	ticketId: int().notNull(),
	userId: int().notNull(),
	message: text().notNull(),
	isInternal: tinyint().default(0).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("idx_ticket").on(table.ticketId),
]);

export const supportTickets = mysqlTable("support_tickets", {
	id: int().autoincrement().notNull(),
	tenantId: int().notNull(),
	userId: int().notNull(),
	subject: varchar({ length: 255 }).notNull(),
	message: text().notNull(),
	status: mysqlEnum(['open','in_progress','resolved','closed']).default('open').notNull(),
	priority: mysqlEnum(['low','normal','high','urgent']).default('normal').notNull(),
	lastReplyAt: timestamp({ mode: 'string' }),
	lastReplyBy: int(),
	resolvedAt: timestamp({ mode: 'string' }),
	resolvedBy: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("idx_tenant").on(table.tenantId),
	index("idx_status").on(table.status),
	index("idx_supportTickets_status").on(table.status),
]);

export const tenants = mysqlTable("tenants", {
	id: int().autoincrement().notNull(),
	subdomain: varchar({ length: 100 }).notNull(),
	customDomain: varchar({ length: 255 }),
	name: varchar({ length: 255 }).notNull(),
	email: varchar({ length: 320 }).notNull(),
	phone: varchar({ length: 50 }),
	logo: text(),
	primaryColor: varchar({ length: 50 }).default('#000000'),
	accentColor: varchar({ length: 50 }).default('#C9A961'),
	baseCountry: varchar({ length: 100 }).default('Brasil'),
	baseCurrency: varchar({ length: 10 }).default('BRL'),
	currencySymbol: varchar({ length: 10 }).default('R$'),
	timezone: varchar({ length: 100 }).default('America/Sao_Paulo'),
	status: mysqlEnum(['active','suspended','cancelled']).default('active').notNull(),
	trialEndsAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("subdomain").on(table.subdomain),
]);

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	openId: varchar({ length: 64 }),
	password: varchar({ length: 255 }),
	name: text(),
	email: varchar({ length: 320 }).notNull(),
	loginMethod: varchar({ length: 64 }),
	role: mysqlEnum(['user','admin']).default('user').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	phone: varchar({ length: 50 }),
	address: text(),
	city: varchar({ length: 100 }),
	state: varchar({ length: 100 }),
	zipCode: varchar({ length: 20 }),
	country: varchar({ length: 100 }).default('Brasil'),
	cpf: varchar({ length: 20 }),
	street: varchar({ length: 255 }),
	number: varchar({ length: 20 }),
	complement: varchar({ length: 100 }),
	neighborhood: varchar({ length: 100 }),
	tenantId: int().default(1).notNull(),
},
(table) => [
	index("users_openId_unique").on(table.openId),
]);
