import { useRoute } from "wouter";
import { ClientLayout } from "@/components/ClientLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertCircle, CheckCircle, FileText, Download, Clock } from "lucide-react";

export default function ClientContract() {
  const [, params] = useRoute("/client/contract/:id");
  const appointmentId = params?.id ? parseInt(params.id) : 0;

  const { data: appointment, isLoading: loadingAppointment } = trpc.appointments.getById.useQuery(
    { id: appointmentId },
    { enabled: appointmentId > 0 }
  );

  const { data: contract, isLoading: loadingContract } = trpc.contracts.getByAppointmentId.useQuery(
    { appointmentId },
    { enabled: appointmentId > 0 }
  );

  const isLoading = loadingAppointment || loadingContract;

  if (isLoading) {
    return (
      <ClientLayout appointmentId={appointmentId}>
        <div className="text-center py-12">
          <p className="text-gray-400">Loading...</p>
        </div>
      </ClientLayout>
    );
  }

  if (!appointment) {
    return (
      <ClientLayout appointmentId={appointmentId}>
        <div className="text-center py-12">
          <AlertCircle className="h-12 w-12 text-red-600 mx-auto mb-4" />
          <p className="text-gray-400">Appointment not found</p>
        </div>
      </ClientLayout>
    );
  }

  const hasContract = !!contract;
  const isSigned = contract?.status === 'signed' || appointment.contractSigned;
  const isSent = contract?.status === 'sent';

  return (
    <ClientLayout appointmentId={appointmentId}>
      <div className="max-w-4xl mx-auto space-y-6">
        <h1 className="text-3xl font-bold mb-6">Contract</h1>

        {/* Contract Status */}
        {hasContract ? (
          <Card className={`p-6 ${isSigned ? 'bg-green-900/20 border-green-600' : 'bg-blue-900/20 border-blue-600'}`}>
            <div className="flex items-center gap-4">
              {isSigned ? (
                <>
                  <CheckCircle className="h-12 w-12 text-green-500" />
                  <div>
                    <h2 className="text-2xl font-semibold text-green-500">Contract Signed</h2>
                    <p className="text-gray-300 mt-1">
                      Contract signed and confirmed
                    </p>
                  </div>
                </>
              ) : (
                <>
                  <FileText className="h-12 w-12 text-blue-500" />
                  <div>
                    <h2 className="text-2xl font-semibold text-blue-500">Contract Available</h2>
                    <p className="text-gray-300 mt-1">
                      Your contract is ready for review
                    </p>
                    {isSent && contract?.sentAt && (
                      <p className="text-gray-400 text-sm mt-1 flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        Sent on {new Date(contract.sentAt).toLocaleDateString('en-GB')}
                      </p>
                    )}
                  </div>
                </>
              )}
            </div>
          </Card>
        ) : (
          <Card className="bg-yellow-900/20 border-yellow-600 p-6">
            <div className="flex items-center gap-4">
              <AlertCircle className="h-12 w-12 text-yellow-500" />
              <div>
                <h2 className="text-2xl font-semibold text-yellow-500">Contract Pending</h2>
                <p className="text-gray-300 mt-1">
                  The contract has not been generated by the photographer yet
                </p>
              </div>
            </div>
          </Card>
        )}

        {/* Contract Details */}
        {hasContract && (
          <Card className="bg-gray-900 border-gray-800 p-6">
            <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Contract Details
            </h3>
            
            <div className="space-y-4">
              <div className="flex justify-between items-center pb-4 border-b border-gray-800">
                <span className="text-gray-400">Client</span>
                <span className="font-semibold">{contract.clientName || appointment.clientName}</span>
              </div>

              {contract.serviceName && (
                <div className="flex justify-between items-center pb-4 border-b border-gray-800">
                  <span className="text-gray-400">Service</span>
                  <span className="font-semibold">{contract.serviceName}</span>
                </div>
              )}

              <div className="flex justify-between items-center pb-4 border-b border-gray-800">
                <span className="text-gray-400">Session Date</span>
                <span className="font-semibold">
                  {appointment.date && new Date(appointment.date).toLocaleDateString('en-GB')}
                </span>
              </div>

              <div className="flex justify-between items-center pb-4 border-b border-gray-800">
                <span className="text-gray-400">Status</span>
                <span className={`font-semibold ${isSigned ? 'text-green-500' : 'text-blue-500'}`}>
                  {isSigned ? 'Signed' : 'Awaiting Signature'}
                </span>
              </div>

              {contract.price && (
                <div className="flex justify-between items-center">
                  <span className="text-gray-400">Total Amount</span>
                  <span className="font-semibold text-xl">
                    £{contract.price}
                  </span>
                </div>
              )}
            </div>
          </Card>
        )}

        {/* Contract Content */}
        {hasContract && contract.content && (
          <Card className="bg-gray-900 border-gray-800 p-6">
            <h3 className="text-xl font-semibold mb-4">Contract Document</h3>
            <div className="bg-white text-black p-8 rounded-lg max-h-[600px] overflow-y-auto" style={{ fontFamily: 'Georgia, serif', fontSize: '13px', lineHeight: '1.8' }}>
              <div style={{ whiteSpace: 'pre-wrap' }}>
                {contract.content}
              </div>
            </div>
          </Card>
        )}

        {/* Download PDF if contractUrl exists */}
        {appointment.contractUrl && (
          <Card className="bg-gray-900 border-gray-800 p-6">
            <Button 
              className="w-full bg-red-600 hover:bg-red-700"
              onClick={() => window.open(appointment.contractUrl!, '_blank')}
            >
              <Download className="h-4 w-4 mr-2" />
              Download Contract (PDF)
            </Button>
          </Card>
        )}

        {/* Help Info */}
        {hasContract && !isSigned && (
          <Card className="bg-blue-900/20 border-blue-600 p-6">
            <p className="text-gray-300">
              <strong>Need to sign the contract?</strong><br />
              Get in touch with the photographer via <a href={`/client/chat/${appointmentId}`} className="text-red-400 underline">chat</a> to arrange the signing.
            </p>
          </Card>
        )}
      </div>
    </ClientLayout>
  );
}
